### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by jermydu** [opencodewin/MediaEditor#61]
-- Configuring done (0.6s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Glslang_OGLCompiler_LIBRARY_RELEASE (ADVANCED)
    linked by target "VkShader" in directory D:/sourcecode/MediaEditor/MediaEditor-master/imgui/addon/ImVulkanShader

-- Generating done (1.8s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by WyvernZhao** [comment]
Are you compiling the latest code from master branch? We DID encounter glslang library linking issue recently due to glslang version upgrade and removed OGLCompiler library which would lead to linking issue. But we've fixed this issue on our platform. Could you tell us what develop environment you are using? Such as: OS=windows, Compiler=MSYS2 mingw64 gcc{?version?}.

**Comment by jermydu** [comment]
> Are you compiling the latest code from master branch? We DID encounter glslang library linking issue recently due to glslang version upgrade and removed OGLCompiler library which would lead to linking issue. But we've fixed this issue on our platform. Could you tell us what develop environment you are using? Such as: OS=windows, Compiler=MSYS2 mingw64 gcc{?version?}. If you're using MSYS2 mingw, could you show me the version of your glslang package by `pacman -Qi mingw-w64-x86_64-glslang`?

compiling the latest code from master branch is ok，thankyou
