### ISSUE TITLE
Problem regarding releases

### ISSUE THREAD

**Issue by MechDR** [opencodewin/MediaEditor#70]
Hello! 😊

Could you also package the symbolic links to `blueprintsdk`, `MediaCore` and `imgui` from the other repos when doing a release please? The `plugin` dir seems to be OK and on track, but not the other symlinks (empty). Would have to dig through GH history to find the right commit that corresponds with the date of that particular release and then use that to build MediaEditor.

**Comment by WyvernZhao** [comment]
Sorry for you inconvenience, but the packaged source code zip file in the release was managed and created by github. I don't know how to and I don't think we have the right to change how it was zipped and what files it includes. I see that your problem is the difficulty to find the corresponding submodule version for a certain version of MEC. My suggestion is to use the following git commands:

**Comment by MechDR** [comment]
See, the problem is, I'm trying to package this for Void Linux and xbps-src has this rule, you have to define the version of the software at the beginning of the template and all of the distfiles, which of course, also include the symlinks to the other repos. The script then takes the sources and downloads them, extracts the content in special build dir, and then tries to build the package. The problem with this scenario is, there is no actual way to obtain the full source at the beginning of the script, but it has to be done afterwards. Sure there are functions and hooks that can be used to do it afterwards, but it just complicates the build process, as you have to add additional dependencies to the template (git, tar, gzip, etc.).

If there is absolutely no other way, sure, this method can be used, but how come the `plugin` dir gets packed with the source, but not the other symlinked repos 🤔?

**Comment by WyvernZhao** [comment]
It's because we are using submodules to group our code into separated blocks. It's a good way to isolate the modules for the ease of developing by different programmers/teams, and it's also good for sharing some fundamental modules across projects since we don't need to maintain copies of the same code. And `plugin` directory was a local directory for 'Media Editor' at v0.9.9, but it's been excluded and become an individual repo now. I'm afraid it's inevitable that you need run some git script to collect all the code at the beginning of your building process 😐
