### ISSUE TITLE
JFYI, build issues downstream nixos

### ISSUE THREAD

**Issue by luzpaz** [opencodewin/MediaEditor#73]
https://github.com/NixOS/nixpkgs/pull/251984  
https://discourse.nixos.org/t/help-packaging-mediaeditor-installphase-existing-pr/32312

**Comment by sizeofbeer** [comment]
We are very sorry. Due to our own reasons, the progress of the project is currently slow done, and in fact, the development progress of the current project has been suspended. We have encountered significant resistance at the development level, and in order to avoid some internal issues, some of the code in the latest version is released in binary packages, which makes it difficult to compile smoothly from v0.9.8  and before. Based on the current feedback, we are trying to provide code that is easy to compile.

At present, the economic environment is not good, and some developers have to turn to other directions. For this project, our developers selflessly provided time, energy, and financial resources, but it is now difficult to have the financial support to complete the promised features. Sorry again.

**Comment by luzpaz** [comment]
bummer, sorry to read that. Thanks for the heads-up

**Comment by sizeofbeer** [comment]
The latest code can now be compiled.
